services:
  # 🐘 PostgreSQL
  postgres:
    image: ankane/pgvector:latest
    container_name: clearcart-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: REMOVED-DB-PASSWORD
      POSTGRES_DB: clearcart
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # 🚀 Clear Cart Backend
  backend:
    build: ./backend
    container_name: clearcart-backend
    depends_on:
      - postgres
    volumes:
      - ./backend/keys:/app/keys:ro                # Server key'leri
      - ./backend/client_keys:/app/keys/client_keys  # Kullanıcı özel key'leri
      - ./backend/user_uploads:/app/user_uploads     # Feedback ve görseller
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:REMOVED-DB-PASSWORD@postgres:5432/clearcart
      - JWT_SECRET=REMOVED-JWT-SECRET
      - ANDROID_CLIENT_ID_FOR_GOOGLE=432849675027-gfnrj2onvvqii8nun2n3kc4evcq0riqd.apps.googleusercontent.com
      - GOOGLE_CLIENT_ID=452101464013-ci3g1qrbpp2d38rhn7moga06geg1ma1j.apps.googleusercontent.com
      - PORT=7860
      - JWT_PRIVATE_KEY_PATH=/app/keys/private.pem
      - JWT_PUBLIC_KEY_PATH=/app/keys/public.pem
      - CLIENT_KEYS_DIR=/app/keys/client_keys       # Kullanıcı key'leri için env değişkeni
    expose:
      - "7860"
    restart: unless-stopped

  ad-b:
    build: ./ad-b
    container_name: clearcart-admin-backend
    depends_on:
      - postgres
    volumes:
    - ./ad-b/product-photos:/app/product-photos
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:REMOVED-DB-PASSWORD@postgres:5432/clearcart
      - JWT_SECRET=REMOVED-JWT-SECRET
      - JWT_PRIVATE_KEY_PATH=/app/keys/private.pem
      - JWT_PUBLIC_KEY_PATH=/app/keys/public.pem
      - CLIENT_KEYS_DIR=/app/keys/client_keys
      - PORT=10031
    expose:
      - "10031"
    restart: unless-stopped

   # 🚇 NGROK Tunnel (backend'e tünel açar)
 
  ngrok:
    image: ngrok/ngrok:latest
    container_name: clearcart-ngrok
    depends_on:
      - backend
      - nginx # Nginx'i de buraya ekleyelim, çünkü tünel Nginx'e gidiyor.
    environment:
      - NGROK_AUTHTOKEN=REMOVED-NGROK-TOKEN
    command: ["http", "clearcart-nginx:80"] # Tünel Nginx Reverse Proxy'ye gidiyor
    restart: unless-stopped

  # 🌐 Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: clearcart-nginx
    depends_on:
      - backend
      - ad-b
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd:rw
    restart: unless-stopped

volumes:
  postgres_data:
